### ISSUE TITLE
Integrate a static site generator?

### ISSUE THREAD

**Issue by juzmach** [code-n-beer/xstack.io#3]
To make the content easily editable.

http://wintersmith.io or http://gohugo.io ?

**Comment by juzmach** [comment]
However, that would bloat the site a bit. Now it's nice and simple.

**Comment by OlliV** [comment]
If we decide to proceed, I vote for hugo 'cause it looks more hipster than wintersmith.

**Comment by juzmach** [comment]
I think we should just focus on the landing page for now. I'm gonna close this one and get back to this one if we need it in the future.
