### ISSUE TITLE
Assign some other port

### ISSUE THREAD

**Issue by OlliV** [code-n-beer/xstack.io#7]
We should assign some other port than 80 so we can use another nginx on the host as a proxy for this.
Another option would be host everything on the host vm without docker, that's because we may wan't to host some other http stuff on the vm without pushing it into this repository.

**Comment by juzmach** [comment]
Yeah I was thinking about that. What port would you like?

**Comment by juzmach** [comment]
Yeah, I was thinking about that. It's a good idea. What port would you like?

**Comment by OlliV** [comment]
maybe 420

**Comment by juzmach** [comment]
Awesome.
